version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: laravelapp
    container_name: laravelapp
    restart: unless-stopped
    tty: true
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=your_root_password"
    volumes:
      - ./:/var/www
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laraveldb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: web_baseball_note
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  npm:
    image: node:16-buster
    platform: linux/amd64
    container_name: laravelnpm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: ["npm", "run", "watch"]

  nginx:
    image: nginx:latest
    container_name: laravelnginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge
